os: linux
language: ruby
rvm:
- 2.7.1

install:
- bundle install

after_success:
- cp ./.travis/_config.yml ./_site

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: source

#notifications:
#  irc:
#    channels:
#    - "ircs://chat.freenode.net:7070/#sfzformat-dev"
#
#    template:
#    - "[%{repository_name}:%{branch}] Build #%{build_number}: %{message}"
#    - "%{author} : %{commit_subject}"
#    - "Commit URL    : https://github.com/%{repository_slug}/commit/%{commit}"
#    - "Build Details : %{build_url}"
